name: CI(first steps)

on:
  push:
    branches:
      - main

jobs:
  lint-and-ts-check-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npm run generate

      - run: npm run lint

      - run: npm run typecheck

      # - run: npm run build